name: Terraform apply

on:
  pull_request:
    branches:
      - prod

env:
  TF_CLOUD_ORGANIZATION: "Looply"
  TF_TOKEN_app_terraform_io: "${{ secrets.TF_API_TOKEN }}"
  CONFIG_DIRECTORY: "./component-library/infra/env/prod"

jobs:
  terraform apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        working-directory: ${{ env.CONFIG_DIRECTORY }}
        run: terraform fmt

      - name: Terraform apply
        working-directory: ${{ env.CONFIG_DIRECTORY }}
        run: terraform apply
